### ISSUE TITLE
I can't get QuickMag running.

### ISSUE THREAD

**Issue by TheRealDjElite** [nexus-prime/QuickMag.jl#9] opened 2023-01-15 17:46 UTC
The "Estimate CPU Performance" menu option gave me `Failed: TaskFailedException(Task (failed) @0x000001ea3f3bee90)`

"Estimate GPU Performance", "BOINC CPU Survey", and "BOINC GPU Survey" menu options give me: `Failed: ArgumentError("\".\\HostFiles\\gpu_srbase.csv\" is not a valid file or doesn't exist")`

UPDATE:
My fix was to remove projects from the WhiteList.csv that were giving me the "not a valid file or doesn't exist" error such as  Einstein@home, Asteroids@home, Yoyo@home, Numberfields@home, Srbase, and Tn-grid.

I reinitialized set up and the only files that were built and saved to the HostFiles were the projects that gave no error.

I can now get 'results' with no errors.

**Comment by nexus-prime** [comment] 2023-02-01 14:49
Duplicate of [Issue #7](https://github.com/nexus-prime/QuickMag.jl/issues/7)

**Closed as completed by nexus-prime** 2023-02-01 14:49 UTC
Labels: duplicate
